
services:
  - type: web
    plan: free
    name: nd-backend-web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn nd_backend.asgi:application -k uvicorn.workers.UvicornWorker' 