# Generated by Django 5.2.7 on 2025-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0003_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
