# Generated by Django 5.2.7 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_openings', '0005_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
