# Generated by Django 5.2.7 on 2025-10-25 12:30

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', base.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
